import { FlashCard } from "src/app/panel/flash-card/my-flash-card/shared/flash-card";

export const FlashCards: FlashCard[] = [
  {
    name: "touchstone_IC1",
    create_date: "1402-5-2",
    update_date: "1402-5-28",
    days_repetition: "4 day",
    repetition_in_day: "once a day",
    from_hours: "10 a.m",
    to_hours: "",
    notify: true,
    quantity: 40,
    status: true,
  },
  {
    name: "touchstone_IC2",
    create_date: "1402-6-2",
    update_date: "1402-7-20",
    days_repetition: "8 day",
    repetition_in_day: "twice a day",
    from_hours: "8 a.m",
    to_hours: "8 p.m",
    notify: true,
    quantity: 120,
    status: true,
  },
  {
    name: "touchstone_IC3",
    create_date: "1401-8-2",
    update_date: "1401-9-20",
    days_repetition: "30 days",
    repetition_in_day: "twice a day",
    from_hours: "10 a.m",
    to_hours: "10 p.m",
    notify: false,
    quantity: 40,
    status: false,
  },
  {
    name: "touchstone_IC1",
    create_date: "1402-5-2",
    update_date: "1402-5-28",
    days_repetition: "4 day",
    repetition_in_day: "once a day",
    from_hours: "10 a.m",
    to_hours: "",
    notify: true,
    quantity: 40,
    status: true,
  },
  {
    name: "touchstone_IC2",
    create_date: "1402-6-2",
    update_date: "1402-7-20",
    days_repetition: "8 day",
    repetition_in_day: "twice a day",
    from_hours: "8 a.m",
    to_hours: "8 p.m",
    notify: true,
    quantity: 120,
    status: true,
  },
  {
    name: "touchstone_IC3",
    create_date: "1401-8-2",
    update_date: "1401-9-20",
    days_repetition: "30 days",
    repetition_in_day: "twice a day",
    from_hours: "10 a.m",
    to_hours: "10 p.m",
    notify: false,
    quantity: 40,
    status: false,
  },
  {
    name: "touchstone_IC2",
    create_date: "1402-6-2",
    update_date: "1402-7-20",
    days_repetition: "8 day",
    repetition_in_day: "twice a day",
    from_hours: "8 a.m",
    to_hours: "8 p.m",
    notify: true,
    quantity: 120,
    status: true,
  },
  {
    name: "touchstone_IC3",
    create_date: "1401-8-2",
    update_date: "1401-9-20",
    days_repetition: "30 days",
    repetition_in_day: "twice a day",
    from_hours: "10 a.m",
    to_hours: "10 p.m",
    notify: false,
    quantity: 40,
    status: false,
  }
]
