export class ExpantionTabelDetails {
  routeActive: string;
  tabActive: string;
  pdf: boolean;
  excel: boolean;
  print: boolean;
  delete: boolean;
  statusChange: boolean;
  groupStatusChange: boolean;
  backStatusChange: boolean;
  backGroupStatusChange: boolean;
  actionDelete: boolean;
  actionCancel: boolean;
  actionInfo: boolean;
  actionEdit: boolean;
  actionView: boolean;
  actionCopy: boolean;
  actionPrint: boolean;
  actionCheck: boolean;
  actionStatusChange: boolean;
  actionBackStatusChange: boolean;
  actionUndo: boolean;
  action: boolean;
  advancedSearch: boolean;
  searchBy? : boolean;
  showHeader? : boolean;
  showFooter: boolean;
  selectedId?: boolean;
  constructor(expationColumnName?: any) {
    expationColumnName = expationColumnName || {};
    this.routeActive = expationColumnName.routeActive;
    this.tabActive = expationColumnName.tabActive;
    this.pdf = expationColumnName.pdf || false;
    this.excel = expationColumnName.excel || false;
    this.print = expationColumnName.print || false;
    this.delete = expationColumnName.delete || false;
    this.statusChange = expationColumnName.statusChange || false;
    this.groupStatusChange = expationColumnName.groupStatusChange || false;
    this.backStatusChange = expationColumnName.backStatusChange || false;
    this.backGroupStatusChange = expationColumnName.backGroupStatusChange || false;
    this.actionDelete = expationColumnName.actionDelete || false;
    this.actionCancel = expationColumnName.actionCancel || false;
    this.actionInfo = expationColumnName.actionInfo || false;
    this.actionEdit = expationColumnName.actionEdit || false;
    this.actionView = expationColumnName.actionView || false;
    this.actionCopy = expationColumnName.actionCopy || false;
    this.actionCheck = expationColumnName.actionCheck || false;
    this.actionPrint = expationColumnName.actionPrint || false;
    this.actionStatusChange = expationColumnName.actionStatusChange || false;
    this.actionBackStatusChange = expationColumnName.actionBackStatusChange || false;
    this.actionUndo = expationColumnName.actionUndo || false;
    this.action = expationColumnName.action || true;
    this.advancedSearch = expationColumnName.advancedSearch || false;
    this.searchBy = expationColumnName.searchBy || false;
    this.showHeader = expationColumnName.showHeader || false;
    this.showFooter = expationColumnName.showFooter || false;
    this.selectedId = expationColumnName.selectedId || false;
  }
}
